version: 0.2

phases:
  pre_build:
    commands:
      #- echo Installing dependencies
      #- apt-get update
      #- apt-get install jq moreutils -y
      #- pip3 install yq
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`

      # This isn't required in the base repo, but having it here makes it possible to just link the buildspec.yml
      # in repositories that use trrf as a submodule (ie. angelman etc.)
      - git submodule update --init

      # CodePipeline loses the file permissions while copying artifacts
      # https://docs.aws.amazon.com/codepipeline/latest/userguide/troubleshooting.html#troubleshooting-file-permissions
      - chmod +x scripts/*.sh
      - chmod +x docker/dev/*.sh
      - chmod +x rdrf/rdrf/scripts/check-calculation.js

      - docker-compose build
      - echo Running tests...
      - scripts/lint.sh
      - scripts/check-migrations.sh
      - scripts/unit-tests.sh
      - scripts/end2end-tests.sh
      - echo Building and tagging the Docker image...
      - docker build -f docker/production/Dockerfile -t $IMAGE_REPO:$APPLICATION_VERSION .

      # docker push used to be in post_build, but post_build is executed even on build failure.
      # We don't want to push the docker image if the build failed for any reason, so we can't do the docker push in post_build.
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO:$APPLICATION_VERSION

artifacts:
  files:
    - '*'
    - 'docker/**/*'
    - 'scripts/**/*'
