version: '3.7'

x-common-env-variables: &common-env-variables
  DEBUG: 0
  TEST_WAIT: 10
  TEST_BROWSER: chrome

  TEST_APP_HOST: serverundertest

  DBSERVER: dbtest
  CLINICAL_DBSERVER: dbclinicaltest
  REPORTING_DBSERVER: dbreportingtest
  CACHESERVER: cachetest

services:
  aloe_dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: eresearchqut/trrf
    command: aloe
    environment:
      <<: *common-env-variables
      WAIT_FOR_RUNSERVER: 1
      RUNSERVER: serverundertest
    volumes:
      - .:/app
      - ./data/aloe/dev:/data

  aloe_prod:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: eresearchqut/trrf
    command: aloe
    environment:
      <<: *common-env-variables
      WAIT_FOR_UWSGI: 1
      UWSGISERVER: serverundertest
      TEST_APP_PORT: 9000
    volumes:
      - .:/app
      - ./data/aloe/prod:/data
