version: '3.7'

services:
  cache:
    image: memcached:1.4

  uwsgi:
    # image: eresearchqut/trrf:${TRRF_VERSION}
    image: ${UWSGI_IMAGE}
    command: uwsgi
    env_file:
      - docker/production/envs/uwsgi
      # the .env file below is appended to by CodeDeploy on the server with environment specific variables
      - .env
    volumes:
      - ./data/prod/:/data
    depends_on:
      - cache

  nginx:
    # TODO hardcoded to the R4 account URL. Set env var instead?
    image: 126579111836.dkr.ecr.ap-southeast-2.amazonaws.com/trrf_nginx_proxy:latest
    ports:
      - 443:443
    depends_on:
      - uwsgi
