version: '3.7'

volumes:
  prod_db_data:
  prod_clinicaldb_data:
  prod_reportingdb_data:

services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=webapp
    volumes:
      - prod_db_data:/var/lib/postgreql/data

  dbclinical:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=webapp
    volumes:
      - prod_clinicaldb_data:/var/lib/postgreql/data

  dbreporting:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=webapp
    volumes:
      - prod_reportingdb_data:/var/lib/postgreql/data

  cache:
    image: memcached:1.4

  uwsgi:
    image: eresearchqut/trrf:${TRRF_VERSION:trrf_version_unset}
    command: uwsgi
    environment:
      - PRODUCTION=1
      - DEBUG=0
      - WAIT_FOR_DB=1
      - WAIT_FOR_CLINICAL_DB=1
      - WAIT_FOR_REPORTING_DB=1
      - WAIT_FOR_CACHE=1
      - DJANGO_FIXTURES=test
      - ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=localhost
      - CACHESERVER=cache
      - DBSERVER=db
      - CLINICAL_DBSERVER=dbclinical
      - REPORTING_DBSERVER=dbreporting
      # TODO think about more about these env variables. Probably use .env files
      # currently just making the PROD stack working on my local machine
      - DBNAME=webapp
      - DBUSER=webapp
      - DBPASS=webapp

      - SECURE_SSL_REDIRECT=0  # Disabling SSL redirect for ELB SSL termination
      - SESSION_COOKIE_SECURE=0
      - CSRF_COOKIE_SECURE=0
    volumes:
      - ./data/prod/:/data
    ports:
      - "9000:9000"
