version: '2'
services:

  # note: the host aliases are to alow the prod stack to be used as a test stack

  dbprod:
    extends:
      file: docker-compose-common.yml
      service: db
    networks:
      default:
        aliases:
          - dbtest

  dbclinicalprod:
    extends:
      file: docker-compose-common.yml
      service: db
    networks:
      default:
        aliases:
          - dbclinicaltest

  cacheprod:
    extends:
      file: docker-compose-common.yml
      service: cache
    networks:
      default:
        aliases:
          - cachetest

  mongoprod:
    extends:
      file: docker-compose-common.yml
      service: mongo
    networks:
      default:
        aliases:
          - mongotest

  nginxprod:
    extends:
      file: docker-compose-common.yml
      service: nginx
    depends_on:
      - uwsgiprod
    networks:
      default:
        aliases:
          - nginxtest

  uwsgiprod:
    image: muccg/rdrf:${BUILD_VERSION}
    command: uwsgi_local
    environment:
      - WAIT_FOR_DB=1
      - WAIT_FOR_CLINICAL_DB=1
      - WAIT_FOR_CACHE=1
      - WAIT_FOR_MONGO=1
      - DJANGO_FIXTURES=test
      - ALLOWED_HOSTS=*
    volumes:
        - uwsgi-prod-data:/data
    depends_on:
      - dbprod
      - dbclinicalprod
      - cacheprod
      - mongoprod
    ports:
      - "9000:9000"
    networks:
      default:
        aliases:
          - uwsgitest

volumes:
  uwsgi-prod-data:
