#
dataselenium:
  extends:
    file: docker-compose-common.yml
    service: dataselenium

# runs the selenium tests against docker-compose-seleniumstack.yml
seleniumtesthost:
  image: muccg/yabi-dev
  command: selenium
  environment:
    - DBUSER=rdrfapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_RUNSERVER=1
    - WAIT_FOR_MONGO=1
  volumes_from:
    - dataselenium
  external_links:
    - rdrf_dbselenium_1:db
    - rdrf_runserverselenium_1:web
    - rdrf_mongoselenium_1:mongo
    - rdrf_seleniumhub_1:hub
    - rdrf_reportingselenium_1:reporting
