version: '3.7'

services:
  dbtest:
    image: postgres:10.7
    volumes:
      - ./docker/dev/devdb-docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    env_file:
      - docker/dev/envs/postgres  # Using same db settings as dev for now
    ports:
      - "5432"

  dbclinicaltest:
    image: postgres:10.7
    volumes:
      - ./docker/dev/devdb-docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    env_file:
      - docker/dev/envs/postgres
    ports:
      - "5432"

  dbreportingtest:
    image: postgres:10.7
    env_file:
      - docker/dev/envs/postgres
    ports:
      - "5432"
