version: '3.7'

volumes:
  local_postgres_data: {}

services:
  db:
    # TODO time to upgrade?
    image: postgres:9.4
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=webapp
    ports:
      - "5432"

  clinicaldb:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=webapp
    ports:
      - "5432"

  reportingdb:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=webapp
    ports:
      - "5432"

  cache:
    # TODO time to upgrade?
    image: memcached:1.4

  runserver:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: eresearchqut/trrf
    environment:
      - WAIT_FOR_DB=1
      - WAIT_FOR_CLINICAL_DB=1
      - PRODUCTION=0
      - WAIT_FOR_REPORTING_DB=1
      - WAIT_FOR_CACHE=1
      - DJANGO_MAILGUN_API_KEY=${DJANGO_MAILGUN_API_KEY}
      - DJANGO_FIXTURES=dev
      - DESIGN_MODE=1
      - PROMS_SYSTEM_URL=http://test.com
    volumes:
      - .:/app
      - ./data/dev/:/data
    ports:
      - "8000:8000"
    depends_on:
      - db
      - clinicaldb
      - reportingdb
      - cache

  node:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile-node
    stop_signal: SIGKILL
    image: eresearchqut/trrf-node
    command: watch
    working_dir: /app/rdrf/rdrf/frontend
    environment:
        YARN_CACHE_FOLDER: /opt/yarn_cache
    volumes:
      - .:/app
      - ./data/dev/:/data
      - ./yarn_cache:/opt/yarn_cache
