version: '3.7'

volumes:
  prod_db_data:
  prod_clinicaldb_data:
  prod_reportingdb_data:

services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=webapp
    volumes:
      - prod_db_data:/var/lib/postgreql/data

  clinicaldb:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=webapp
    volumes:
      - prod_clinicaldb_data:/var/lib/postgreql/data

  reportingdb:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=webapp
    volumes:
      - prod_reportingdb_data:/var/lib/postgreql/data

  cache:
    image: memcached:1.4

  uwsgi:
    # image: eresearchqut/trrf:${TRRF_VERSION}
    image: ${UWSGI_IMAGE}
    command: uwsgi
    env_file:
      - docker/production/envs/uwsgi
      # TODO the .env file below is populated by CodeDeploy on the server with environment specific variables
      - .env
    volumes:
      - ./data/prod/:/data
    depends_on:
      - db
      - clinicaldb
      - reportingdb
      - cache

  nginx:
    build:
      context: ./docker/production/nginx/
    # TODO build this image on the build server, push it to ECR and only refer to it here
    image: trrf_production_nginx
    ports:
      - 443:443
    depends_on:
      - uwsgi
