#
dataselenium:
  extends:
    file: docker-compose-seleniumstack.yml
    service: dataselenium

# runs the lettuce tests against docker-compose-teststack.yml
lettucehost:
  image: muccg/rdrf-dev
  command: lettuce
  environment:
    - WAIT_FOR_WEB=1
  volumes_from:
    - dataselenium      
  external_links:
    - rdrf_runservertest_1:web
    - rdrf_seleniumhub_1:hub
