version: '3.7'

services:
  serverundertest:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: docker.pkg.github.com/scriptsmith/gh-actions-test/runserver
    working_dir: /data
    environment:
      - CONSOLE_LOG_LEVEL=DEBUG
    env_file:
      - docker/dev/envs/postgres
      - docker/dev/envs/runserver
      - docker/dev/envs/runservertest
    volumes:
      - .:/app
      - ./data/test/:/data
    ports:
      - 8000
    depends_on:
      - dbtest
      - dbclinicaltest
      - dbreportingtest
